language: python
python:
    - "2.7"
notifications:
    email: virtualcommons-dev@googlegroups.com
env: DB=postgres
services:
    - redis
before_script:
    - psql -c 'create user vcweb CREATEDB;' -U postgres
    - psql -c 'create database vcweb' -U vcweb -d template1
    - cp vcweb/settings/local.py.example vcweb/settings/local.py
install: "pip install -r requirements.txt"
script: fab coverage
after_success:
    - coveralls
